[[pages]]
path = "overview.py"
name = "Overview"
icon = "ðŸ“Š"

[[pages]]
path = "model_validation.py"
name = "Model Validation"
icon = "ðŸ“Š"

[[pages]]
path = "forecast_cpi.py"
name = "CPI Forecasting"
icon = "ðŸ“Š"

[[pages]]
path = "cpi_percent_change.py"
name = "Monthly CPI Trends"
icon = "ðŸ“ˆ"

[[pages]]
path = "cpi_percent_change_y.py"
name = "Yearly CPI Trends"
icon = "ðŸ“‰"


[theme]
base="light"
primaryColor="#C982EF"
textColor="#3b3b3b"
font = "sans serif"
